### ISSUE TITLE
yntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by nkli** [shaodahong/jd-happy#2]
运行报错
puppeteer.launch().then(async browser => {
                        ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by shaodahong** [comment]
@nkli node版本多少
